apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-cust-svc
  namespace: demo
spec:
  selector:
    matchLabels:
      app: ext-cust-svc
  template:
    metadata:
      labels:
        app: ext-cust-svc
    spec:
      containers:
        - name: server
          image: gcr.io/vino9-276317/demoapp/ext-cust-svc:43667366f1a1366a28d818c937341a35b6aeda29
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ext-cust-svc
  namespace: demo
  labels:
    app: ext-cust-svc
    service: ext-cust-svc
spec:
  type: ClusterIP
  selector:
    app: ext-cust-svc
  ports:
    - name: http
      port: 8080
